### ISSUE TITLE
bem start impossible due to missing EventLoop

### ISSUE THREAD

**Issue by emanuel-b-q** [Thomas-Gelf/icingaweb2-module-bem#2]
Hello Thomas,
I discovered that using RedHat php7 (from SCL) the daemon is not able to start.
It fails with the following message:

PHP Fatal error:  Uncaught Error: Class 'React\EventLoop\Factory' not found in /usr/local/icingaweb-modules/bem/library/Bem/MainRunner.php:60
Stack trace:
#0 /usr/local/icingaweb-modules/bem/application/clicommands/DaemonCommand.php(9): Icinga\Module\Bem\MainRunner->run()
#1 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Bem\Clicommands\DaemonCommand->runAction()
#2 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#3 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#4 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#5 {main}
  thrown in /usr/local/icingaweb-modules/bem/library/Bem/MainRunner.php on line 60

Fatal error: Uncaught Error: Class 'React\EventLoop\Factory' not found in /usr/local/icingaweb-modules/bem/library/Bem/MainRunner.php:60
Stack trace:
#0 /usr/local/icingaweb-modules/bem/application/clicommands/DaemonCommand.php(9): Icinga\Module\Bem\MainRunner->run()
#1 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Bem\Clicommands\DaemonCommand->runAction()
#2 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#3 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#4 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#5 {main}
  thrown in /usr/local/icingaweb-modules/bem/library/Bem/MainRunner.php on line 60

Installed RPMs for php7 are:

rh-php71-php-pdo-7.1.8-1.el7.x86_64
rh-php71-php-intl-7.1.8-1.el7.x86_64
rh-php71-php-soap-7.1.8-1.el7.x86_64
rh-php71-runtime-1-1.el7.x86_64
rh-php71-php-pear-1.10.4-1.el7.noarch
rh-php71-php-mbstring-7.1.8-1.el7.x86_64
rh-php71-php-common-7.1.8-1.el7.x86_64
rh-php71-php-xml-7.1.8-1.el7.x86_64
rh-php71-php-mysqlnd-7.1.8-1.el7.x86_64
rh-php71-php-fpm-7.1.8-1.el7.x86_64
rh-php71-php-json-7.1.8-1.el7.x86_64
rh-php71-php-process-7.1.8-1.el7.x86_64
rh-php71-php-pgsql-7.1.8-1.el7.x86_64
rh-php71-php-gd-7.1.8-1.el7.x86_64
rh-php71-php-zip-7.1.8-1.el7.x86_64
rh-php71-1-1.el7.x86_64
rh-php71-php-cli-7.1.8-1.el7.x86_64
rh-php71-php-ldap-7.1.8-1.el7.x86_64

I noticed that we had a package :

php-react-event-loop-0.4.3-1.el7.remi.noarch

installed befor, unfortunately it doesn't exist in php7
I found the following: 
https://github.com/reactphp/event-loop/issues/55
Is that somehow related to the function you're using?
Thanks upfront:

    Emanuel

**Comment by lazyfrosch** [comment]
Looks like 2 problems:

1. React must be installed externally - @emanuel-b-q tried to do this with the RPM package
2. React is still not in auto-loading, so this doesn't work

Should we embed the required libraries as vendor?

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: no, there is [ipl-3rdparty](https://github.com/Thomas-Gelf/ipl-3rdparty) for this. Didn't attach installation instructions as the build process might change before moving to the Icinga namespace. Do not clone the repo but download the latest release and install it like an Icinga Web 2 module. The name doesn't matter, I currently use `ipl3rdparty`. Just make sure to not use a dash in the name (`ipl-3rdparty` is not ok).

**Comment by lazyfrosch** [comment]
The new dependency for this is: https://github.com/Icinga/icingaweb2-module-reactbundle

**Comment by Thomas-Gelf** [comment]
Correct, thank you. The old link redirects there - I'll close this issue.
